robot_configuration:
  robot_name: "g1_robot"
  robot_model: "g1"
  description_file_type: "xacro"
  network_interface: "enP8p1s0"
  tita_namespace: ""
  openai_api_key: ""
  wifi_interface: "wlan0"
  wifi_ssid: "HUAWEI-AX6"
  wifi_password: "huawei7n"
  default_map: "rtabmap.db"
  default_static_map: "accumulated.yaml"
